don't force user to use environment overrides

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -6,7 +6,9 @@ WORKDIR /api
 
 # Copy only critical config files
 COPY api/package.json api/package-lock.json ./
-COPY api/.env ./
+
+# .env only needed for overrides, copy if created
+RUN test -f api/.env && cp api/.env . || echo ".env not found, skipping"
 
 # Install dependencies inside the container
 RUN npm install
